using Jomla.Application.Common.DTOs;
using Jomla.Application.Common.Interfaces;
using Jomla.Application.Features.GroupRequests.Commands.CreateGroupRequest;
using Jomla.Application.Jobs.Agents;
using Jomla.Application.Jobs.JobDispatcher;
using Jomla.Domain;
using Jomla.Domain.Entities;
using MediatR;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;

public class CreateGroupRequestCommandHandler : IRequestHandler<CreateGroupRequestCommand, CreateGroupRequestResponse>
{
    private readonly IAppDbContext _context;
    private readonly IMediator _mediator;
    private readonly ICategoryAgent _categoryAgent;
    private readonly IBackgroundJobDispatcher _jobDispatcher;
    private readonly IImageService _imageService;

    public CreateGroupRequestCommandHandler(
        IAppDbContext context,
        IMediator mediator,
        ICategoryAgent categoryAgent,
        IBackgroundJobDispatcher jobDispatcher,
        IImageService imageService)
    {
        _context = context;
        _mediator = mediator;
        _categoryAgent = categoryAgent;
        _jobDispatcher = jobDispatcher;
        _imageService = imageService;
    }

    public async Task<CreateGroupRequestResponse> Handle(CreateGroupRequestCommand request, CancellationToken cancellationToken)
    {
        // Step 1: Get all categories and resolve the category ID using the CategoryAgent 
        var categories = await _context.Categories
            .Include(C => C.Parent)
            .ToListAsync(cancellationToken);

        if (categories.Count == 0)
        {
            return new CreateGroupRequestResponse(false, null, "No categories exist in the system.");
        }

        var categoryDtos = categories.Select(c => new CategoryDto(
             c.Id,
             c.Parent != null ? $"{c.Parent.Name} > {c.Name}" : c.Name
        ));

        Guid categoryId;
        try
        {
            categoryId = await _categoryAgent.ResolveCategoryAsync(request.Title, categoryDtos, cancellationToken);
        }
        catch
        {
            var fallbackCategory = categories.FirstOrDefault(c => c.Name.Equals("Other", StringComparison.OrdinalIgnoreCase))
                ?? categories.FirstOrDefault(c => c.Name.Contains("Other", StringComparison.OrdinalIgnoreCase) || c.Name.Contains("General", StringComparison.OrdinalIgnoreCase))
                ?? categories.FirstOrDefault();

            if (fallbackCategory == null)
            {
                return new CreateGroupRequestResponse(false, null, "Failed to resolve a fallback category.");
            }

            categoryId = fallbackCategory.Id;
        }

        var imageUrls = new List<string>();

        // Step 1.5: Upload images and get their URLs
        if (request.Images is not null)
        {
            foreach (var image in request.Images)
            {
                var url = await _imageService.UploadImageAsync(
                    image,
                    cancellationToken);

                imageUrls.Add(url);
            }
        }

        // Step 2: Create GroupRequest (Id and CreatedAt will be generated by the database)
        var groupRequest = new GroupRequest
        {
            InitiatorId = request.InitiatorId,
            CategoryId = categoryId,
            Title = request.Title,
            Description = request.Description,
            ImageUrls = imageUrls.Count > 0 ? JsonSerializer.Serialize(imageUrls) : null,
            CurrentQuantity = request.Quantity,
            Status = GroupRequestStatus.PendingReview,
            ModerationStatus = ModerationStatus.Pending
        };

        _context.GroupRequests.Add(groupRequest);

        // Step 3: Create GroupRequestParticipant for the initiator (JoinedAt is database-generated)
        // GroupRequest is set as navigation property since GroupRequest.Id is not populated yet
        var participant = new GroupRequestParticipant
        {
            GroupRequest = groupRequest,
            BuyerId = request.InitiatorId,
            Quantity = request.Quantity,
            Status = GroupRequestParticipantStatus.Active
        };

        _context.GroupRequestParticipants.Add(participant);

        // Step 4: Save transactions to the database
        await _context.SaveChangesAsync(cancellationToken);

        // Step 5: Fire the moderation job for the newly created group request
        _jobDispatcher.Enqueue<IModerateGroupRequestJob>(j =>
            j.ExecuteAsync(groupRequest.Id, CancellationToken.None));

        return new CreateGroupRequestResponse(true, groupRequest.Id, null);
    }
}